name: msvc

on:
  push:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'putils'
  pull_request:
    branches: [ main ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.inl'
      - '**/CMakeLists.txt'
      - '**.cmake'
      - 'putils'
  workflow_dispatch:

jobs:
  build:
    uses: phisko/cmake-cxx-conan/.github/workflows/test.yml@main
    with:
      os: windows-latest
      cmake_options: -DKENGINE_ALL_SYSTEMS=ON -DKENGINE_TESTS=ON
